name: nicekg_analysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - ca-certificates
  - ipykernel
  - matplotlib
  - openssl
  - pandas
  - python=3.11
  - rdflib
  - seaborn
  - sparqlwrapper
  - venn
  - tqdm
  - python-dotenv
  - pycountry
  - openai
  - networkx

